# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "172.16.1.2"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = "4"
   end
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  sudo apt-get install -y curl openssh-server ca-certificates
  curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
  sudo EXTERNAL_URL="http://gitlab.test" apt-get install gitlab-ce
  SHELL
end
